apiVersion: apps/v1
kind: Deployment
metadata:
  name: antaeus-deploy
  labels:
    app: antaeus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antaeus
  template:
    metadata:
      labels:
        app: antaeus
    spec:
      containers:
      - name: antaeus-latest
        image: nwillems/antaeus:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: PAYMENT_PROVIDER_ENDPOINT
          value: "http://payment-service:80"
        resources: # Should probably do some profiling about this
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /rest/health
            port: 8000
          initialDelaySeconds: 720
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /rest/health
            port: 8000
          initialDelaySeconds: 720
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: antaeus-service
spec:
  type: LoadBalancer
  selector:
    app: antaeus
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
