apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deploy
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment-latest
        image: nwillems/payment:c0586788a41f323ddfbdd69e4f32df983ba1e67b
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources: # Should probably do some profiling about this
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
